// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjb6VXsirMQxX3PnnlI8Z7FYY3M7Oq04Q',
    appId: '1:93822452646:web:f3fd7acd47f70a42880567',
    messagingSenderId: '93822452646',
    projectId: 'boost-solutions',
    authDomain: 'boost-solutions.firebaseapp.com',
    storageBucket: 'boost-solutions.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALZa2sU-jedS_vAeFXyl_6FLQx-_00SLs',
    appId: '1:93822452646:android:c482301d433f7306880567',
    messagingSenderId: '93822452646',
    projectId: 'boost-solutions',
    storageBucket: 'boost-solutions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQdYhjKdvavC7djYrR-hZkpln176KyVYE',
    appId: '1:93822452646:ios:b95fb75940dcf7ea880567',
    messagingSenderId: '93822452646',
    projectId: 'boost-solutions',
    storageBucket: 'boost-solutions.firebasestorage.app',
    iosBundleId: 'com.mohasagorit.boostSolutions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQdYhjKdvavC7djYrR-hZkpln176KyVYE',
    appId: '1:93822452646:ios:b95fb75940dcf7ea880567',
    messagingSenderId: '93822452646',
    projectId: 'boost-solutions',
    storageBucket: 'boost-solutions.firebasestorage.app',
    iosBundleId: 'com.mohasagorit.boostSolutions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjb6VXsirMQxX3PnnlI8Z7FYY3M7Oq04Q',
    appId: '1:93822452646:web:f18f03863a743117880567',
    messagingSenderId: '93822452646',
    projectId: 'boost-solutions',
    authDomain: 'boost-solutions.firebaseapp.com',
    storageBucket: 'boost-solutions.firebasestorage.app',
  );
}
