name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: iOS Build
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Flutter Pub Get
        run: flutter pub get

      # Select correct Xcode version (15.4 includes iOS 17 SDK + Swift 5.9)
      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode_15.4.app"

      - name: Export Xcode path
        run: echo "DEVELOPER_DIR=/Applications/Xcode_15.4.app/Contents/Developer" >> $GITHUB_ENV

      # Install CocoaPods and Pods
      - name: Install CocoaPods
        working-directory: ios
        run: |
          sudo gem install cocoapods --no-document
          pod repo update
          pod install --verbose

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Create Payload folder
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move Runner.app
        run: mv Runner.app Payload/
        working-directory: build/ios/iphoneos

      - name: Zip IPA
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
